### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by tengfei-emory** [vdblab/FLORAL#1]
- [x] Further evaluate the current implementation of the generic function
- [x] Add more documentations on recommended way of feature selection / 2-stage procedure after fitting the model
- [x] Add documentations to the output quantities from the model
- [x] Add standard testing code for many different scenarios
- [x] Add a test coverage workflow
- [x] Add examples for longitudinal covariate Cox model and competing risks model (next phase)
- [ ] Try to incorporate `hardhat`-like user-friendly input way
- [ ] Define an output object class
- [ ] Develop `print`, `plot`, `summary` functions to allow easy interpretation of the results
- [x] Launch a website when moving the package to public domain
- [x] Add tests for specific outputs
- [x] `mcv.FLORAL`: adding effect size summary across cross-validations
